`timescale 1ns/1ps

module tb_c1_r1_debayer_bilinear;

    localparam integer FRAME_WIDTH = 10;
    localparam integer FRAME_HEIGHT = 8;
    localparam integer X_BITS = $clog2(FRAME_WIDTH);
    localparam integer Y_BITS = $clog2(FRAME_HEIGHT);
    localparam integer CASE_COUNT = 48;
    localparam integer INPUTS_PER_CASE = FRAME_WIDTH * FRAME_HEIGHT;
    localparam integer OUTPUTS_PER_CASE = (FRAME_WIDTH - 2) * (FRAME_HEIGHT - 2);
    localparam integer TOTAL_INPUTS = CASE_COUNT * INPUTS_PER_CASE;
    localparam integer TOTAL_OUTPUTS = CASE_COUNT * OUTPUTS_PER_CASE;

    logic clk;
    logic rst;
    logic in_valid;
    logic in_sof;
    logic in_eol;
    logic in_eof;
    logic [X_BITS-1:0] in_x;
    logic [Y_BITS-1:0] in_y;
    logic [9:0] in_raw10;
    logic [1:0] cfg_bayer_pattern;
    logic cfg_crop_x_parity;
    logic cfg_crop_y_parity;

    logic out_valid;
    logic out_sof;
    logic out_eol;
    logic out_eof;
    logic [X_BITS-1:0] out_x;
    logic [Y_BITS-1:0] out_y;
    logic [9:0] out_r10;
    logic [9:0] out_g10;
    logic [9:0] out_b10;

    logic [9:0] input_memory [0:TOTAL_INPUTS-1];
    logic [48:0] expected_memory [0:TOTAL_OUTPUTS-1];
    logic [5:0] case_config_memory [0:CASE_COUNT-1];

    integer case_index;
    integer x_index;
    integer y_index;
    integer input_index;
    integer output_index;
    integer timeout_index;
    integer combination_index;
    integer kind_index;
    logic [47:0] case_coverage;
    logic expect_next_output;
    logic drive_done;
    logic [48:0] expected_record;
    logic [29:0] expected_rgb;
    logic [7:0] expected_x;
    logic [7:0] expected_y;

    always #5 clk = ~clk;

    c1_r1_debayer_bilinear #(
        .FRAME_WIDTH(FRAME_WIDTH),
        .FRAME_HEIGHT(FRAME_HEIGHT)
    ) dut (
        .clk,
        .rst,
        .in_valid,
        .in_sof,
        .in_eol,
        .in_eof,
        .in_x,
        .in_y,
        .in_raw10,
        .cfg_bayer_pattern,
        .cfg_crop_x_parity,
        .cfg_crop_y_parity,
        .out_valid,
        .out_sof,
        .out_eol,
        .out_eof,
        .out_x,
        .out_y,
        .out_r10,
        .out_g10,
        .out_b10
    );

    // Compare only against records generated by the independent Python R1
    // Golden.  The testbench intentionally contains no Debayer calculation.
    always @(negedge clk) begin
        if (rst) begin
            output_index = 0;
            expect_next_output = 1'b0;
        end else begin
            if (expect_next_output && !out_valid)
                $fatal(1, "R1 Debayer lost one-pixel-per-clock output within a row");
            if (!out_valid && (out_sof || out_eol || out_eof))
                $fatal(1, "R1 Debayer asserted a sideband without out_valid");

            if (out_valid) begin
                if (output_index >= TOTAL_OUTPUTS)
                    $fatal(1, "R1 Debayer emitted an unexpected extra pixel");
                expected_record = expected_memory[output_index];
                expected_rgb = expected_record[29:0];
                expected_x = expected_record[37:30];
                expected_y = expected_record[45:38];

                if ({out_r10, out_g10, out_b10} !== expected_rgb)
                    $fatal(1,
                        "R1 Debayer RGB mismatch index=%0d got=%03h/%03h/%03h expected=%03h/%03h/%03h",
                        output_index, out_r10, out_g10, out_b10,
                        expected_rgb[29:20], expected_rgb[19:10], expected_rgb[9:0]);
                if ((out_x !== expected_x[X_BITS-1:0]) ||
                    (out_y !== expected_y[Y_BITS-1:0]))
                    $fatal(1,
                        "R1 Debayer coordinate mismatch index=%0d got=(%0d,%0d) expected=(%0d,%0d)",
                        output_index, out_x, out_y, expected_x, expected_y);
                if ((out_sof !== expected_record[46]) ||
                    (out_eol !== expected_record[47]) ||
                    (out_eof !== expected_record[48]))
                    $fatal(1,
                        "R1 Debayer sideband mismatch index=%0d got=%b%b%b expected=%b%b%b",
                        output_index, out_sof, out_eol, out_eof,
                        expected_record[46], expected_record[47], expected_record[48]);

                expect_next_output = !out_eol;
                output_index = output_index + 1;
            end else begin
                expect_next_output = 1'b0;
            end
        end
    end

    initial begin
        $readmemh("r1_debayer_input.hex", input_memory);
        $readmemh("r1_debayer_expected.hex", expected_memory);
        $readmemh("r1_debayer_cases.hex", case_config_memory);

        clk = 1'b0;
        rst = 1'b1;
        in_valid = 1'b0;
        in_sof = 1'b0;
        in_eol = 1'b0;
        in_eof = 1'b0;
        in_x = '0;
        in_y = '0;
        in_raw10 = 10'd0;
        cfg_bayer_pattern = 2'b00;
        cfg_crop_x_parity = 1'b0;
        cfg_crop_y_parity = 1'b0;
        input_index = 0;
        case_coverage = 48'd0;
        drive_done = 1'b0;

        repeat (5) @(negedge clk);
        rst = 1'b0;

        // Frames are intentionally back-to-back.  This checks that neither
        // line memory nor the next frame's CFA configuration contaminates the
        // final pipelined output of the preceding frame.
        for (case_index = 0; case_index < CASE_COUNT; case_index = case_index + 1) begin
            kind_index = case_config_memory[case_index][5:4];
            if (kind_index > 2)
                $fatal(1, "invalid vector kind %0d in case %0d", kind_index, case_index);
            combination_index = (case_config_memory[case_index][1:0] * 4) +
                                (case_config_memory[case_index][3] * 2) +
                                case_config_memory[case_index][2];
            case_coverage[combination_index * 3 + kind_index] = 1'b1;

            for (y_index = 0; y_index < FRAME_HEIGHT; y_index = y_index + 1) begin
                for (x_index = 0; x_index < FRAME_WIDTH; x_index = x_index + 1) begin
                    @(negedge clk);
                    if ((x_index == 0) && (y_index == 0)) begin
                        // Change configuration together with the new SOF,
                        // after the preceding EOF has already been sampled.
                        cfg_bayer_pattern = case_config_memory[case_index][1:0];
                        cfg_crop_x_parity = case_config_memory[case_index][2];
                        cfg_crop_y_parity = case_config_memory[case_index][3];
                    end
                    in_valid = 1'b1;
                    in_sof = (x_index == 0) && (y_index == 0);
                    in_eol = (x_index == FRAME_WIDTH - 1);
                    in_eof = (x_index == FRAME_WIDTH - 1) &&
                             (y_index == FRAME_HEIGHT - 1);
                    in_x = x_index[X_BITS-1:0];
                    in_y = y_index[Y_BITS-1:0];
                    in_raw10 = input_memory[input_index];
                    input_index = input_index + 1;
                end
            end
        end

        @(negedge clk);
        in_valid = 1'b0;
        in_sof = 1'b0;
        in_eol = 1'b0;
        in_eof = 1'b0;
        drive_done = 1'b1;

        if (input_index != TOTAL_INPUTS)
            $fatal(1, "R1 Debayer consumed %0d inputs, expected %0d",
                   input_index, TOTAL_INPUTS);
        if (case_coverage !== {48{1'b1}})
            $fatal(1, "R1 Debayer vector coverage incomplete: %012h", case_coverage);

        for (timeout_index = 0; timeout_index < 200; timeout_index = timeout_index + 1) begin
            @(negedge clk);
            if (output_index == TOTAL_OUTPUTS) begin
                repeat (4) @(negedge clk);
                if (out_valid)
                    $fatal(1, "R1 Debayer emitted data after the expected stream ended");
                $display("C1_R1_DEBAYER_PASS cases=%0d input=%0d output=%0d",
                         CASE_COUNT, TOTAL_INPUTS, TOTAL_OUTPUTS);
                $finish;
            end
        end
        $fatal(1, "R1 Debayer timeout output=%0d expected=%0d drive_done=%0d",
               output_index, TOTAL_OUTPUTS, drive_done);
    end

endmodule
