"""Independent frozen-layout checks, DAG variants and backend rejection tests."""
import dataclasses
from pathlib import Path
import sys
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'model'))
from r2_execution_plan import (
    ACT_RELU, FRAME, FLAG_RESIDUAL_VALID, Node, OP_RESIDUAL_ADD,
    backend_mode, lower, microstyle_nodes, microstyle_plan, render_sv,
)


def signatures(steps):
    return [{k: v for k, v in dataclasses.asdict(s).items() if k not in ('name', 'inputs', 'physical_inputs')} for s in steps]


class PlanTests(unittest.TestCase):
    def test_frozen_parameter_and_slot_contract(self):
        p = microstyle_plan()
        self.assertEqual(len(p), 22)
        self.assertEqual(sum(s.parameter_beats for s in p), 2333)
        # Independent retained graph/golden contract; not generated by lower().
        destinations = {0: 0, 1: 1, 2: 0, 3: 2, 4: 0, 5: 2, 6: 0, 7: 1, 8: 0, 9: 1,
                        10: 0, 11: 2, 12: 0, 13: 2, 15: 0, 16: 1, 18: 0, 19: 1, 20: 0}
        self.assertEqual({s.index: s.dst_slot for s in p if not s.view}, destinations)
        self.assertEqual([s.index for s in p if s.virtual_up2], [15, 18])
        self.assertEqual([s.index for s in p if s.view], [14, 17, 21])
        self.assertEqual([s.index for s in p if s.input_rgb], [0])
        self.assertEqual([s.index for s in p if s.output_rgb], [20])
        self.assertEqual([s.index for s in p if s.last], [21])
        self.assertEqual([p[i].skip_slot for i in (5, 9, 13)], [1, 2, 1])

    def test_tensor_ownership_replay(self):
        owners = {}
        for step in microstyle_plan():
            if step.view:
                continue
            for n, source in enumerate(step.physical_inputs):
                if source != FRAME:
                    self.assertEqual(owners[step.src_slot if n == 0 else step.skip_slot], source)
            if not step.output_rgb:
                self.assertNotIn(step.dst_slot, [step.src_slot, step.skip_slot] if len(step.inputs) == 2 else
                                 ([] if step.input_rgb else [step.src_slot]))
                owners[step.dst_slot] = step.name

    def test_names_do_not_select_kernel_or_bank(self):
        nodes = microstyle_nodes()
        names = {n.spec.name: f'tensor_{i}' for i, n in enumerate(nodes)} | {FRAME: FRAME}
        renamed = [Node(dataclasses.replace(n.spec, name=names[n.spec.name]), tuple(names[x] for x in n.inputs)) for n in nodes]
        self.assertEqual(signatures(lower(nodes)), signatures(lower(renamed)))

    def test_graph_variant_moves_views_and_terminal(self):
        nodes = microstyle_nodes()
        keep = [n for n in nodes if not n.spec.name.startswith('res1.')]
        keep = [Node(n.spec, tuple('res0.add_relu' if x == 'res1.add_relu' else x for x in n.inputs)) for n in keep]
        p = lower(keep)
        self.assertEqual(len(p), 18)
        self.assertEqual([s.index for s in p if s.view], [10, 13, 17])
        self.assertEqual([s.index for s in p if s.virtual_up2], [11, 14])
        self.assertEqual([s.index for s in p if s.output_rgb], [16])
        self.assertEqual([s.index for s in p if s.last], [17])
        # This proves planning only, not numeric execution of the variant.
        self.assertNotIn("5'd21:begin", render_sv(p))

    def test_geometry_changes_not_parameter_or_bank_mapping(self):
        ref = microstyle_plan()
        for w, h in ((4, 4), (8, 12), (12, 8), (32, 32), (640, 4), (4, 480), (636, 476)):
            p = microstyle_plan(w, h)
            self.assertEqual([(s.mode, s.parameter_beats, s.src_slot, s.dst_slot) for s in p],
                             [(s.mode, s.parameter_beats, s.src_slot, s.dst_slot) for s in ref])

    def test_geometry_and_two_bank_rejection(self):
        for w, h in ((3, 4), (644, 480), (640, 484), (640, 479)):
            with self.assertRaises(ValueError):
                microstyle_plan(w, h)
        with self.assertRaisesRegex(ValueError, 'workspace banks'):
            lower(microstyle_nodes(), banks=2)
        with self.assertRaisesRegex(ValueError, 'maximum supported'):
            render_sv(microstyle_plan(32, 32), 32, 32)

    def test_missing_forward_duplicate_and_dead_nodes(self):
        nodes = microstyle_nodes()
        variants = [nodes[:1]+[Node(nodes[1].spec, ('missing',))]+nodes[2:],
                    nodes[:1]+[Node(nodes[1].spec, (nodes[2].spec.name,))]+nodes[2:],
                    [nodes[0], nodes[0]]+nodes[1:]]
        # Bypass all res1 work without removing it: unreachable operations.
        variants.append([Node(n.spec, tuple('res0.add_relu' if x == 'res1.add_relu' else x for x in n.inputs))
                         if n.spec.name.startswith('res2.') else n for n in nodes])
        for bad in variants:
            with self.assertRaises(ValueError):
                lower(bad)

    def test_shape_weight_flags_and_name_rejection(self):
        nodes = microstyle_nodes()
        for change in (dict(input_channels=16), dict(weight_count=0), dict(activation=7), dict(flags=0), dict(name='bad\nendmodule')):
            with self.assertRaises(ValueError):
                lower([Node(dataclasses.replace(nodes[0].spec, **change), nodes[0].inputs)]+nodes[1:])

    def test_no_multiple_consumer_virtual_alias(self):
        nodes = microstyle_nodes()
        add = dataclasses.replace(nodes[5].spec, name='extra.add', input_width=320, output_width=320,
                                  input_height=240, output_height=240)
        variant = nodes[:16]+[Node(add, (nodes[15].spec.name, nodes[14].spec.name))]+[
            Node(nodes[16].spec, ('extra.add',))]+nodes[17:]
        with self.assertRaisesRegex(ValueError, 'one DW consumer'):
            lower(variant)

    def test_backend_capability_and_capacity_rejection(self):
        nodes = microstyle_nodes()
        cases = [(dataclasses.replace(nodes[2].spec, output_channels=32), 160, False),
                 (nodes[2].spec, 513, False), (nodes[3].spec, 341, False),
                 (dataclasses.replace(nodes[5].spec, input_channels=16, output_channels=16), 160, False),
                 (dataclasses.replace(nodes[0].spec, stride=1), 640, False)]
        for spec, width, virtual in cases:
            with self.assertRaises(ValueError):
                backend_mode(spec, width, virtual)

    def test_generated_rom_is_current(self):
        self.assertEqual((ROOT/'rtl/r2/c1_r2_microstyle_plan.sv').read_text(), render_sv(microstyle_plan()))

    def test_small_plan_cannot_masquerade_as_native_rom(self):
        with self.assertRaisesRegex(ValueError, 'frame envelope'):
            render_sv(microstyle_plan(320, 240))
        with self.assertRaisesRegex(ValueError, 'instruction sequence'):
            render_sv(microstyle_plan()[:-1])


if __name__ == '__main__':
    unittest.main(verbosity=2)
