`timescale 1ns/1ps
// Generated by model/r2_execution_plan.py from explicit operator/tensor edges.
// Compile-time plan, not writable microcode. Regenerate and revalidate after
// graph changes; backend capability checks intentionally reject unsupported CNNs.
module c1_r2_microstyle_plan (
    input wire [4:0] index,
    input wire [10:0] frame_width,
    input wire [9:0] frame_height,
    output logic valid,last,input_rgb,output_rgb,virtual_up2,view,
    output logic [2:0] mode,
    output logic [5:0] cin,cout,
    output logic [10:0] src_width,dst_width,
    output logic [9:0] src_height,dst_height,
    output logic [1:0] src_slot,dst_slot,skip_slot,
    output logic [15:0] parameter_beats,
    output logic [4:0] parameter_block
);
    always_comb begin
        valid=0;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=1;
        mode=0;cin=0;cout=0;src_width=0;dst_width=0;src_height=0;dst_height=0;
        src_slot=0;dst_slot=0;skip_slot=0;parameter_beats=0;parameter_block=0;
        case(index)

            5'd0:begin // encoder1.conv3x3_s2
                valid=1;last=0;input_rgb=1;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd4;cin=6'd3;cout=6'd12;
                src_width=frame_width>>0;src_height=frame_height>>0;dst_width=frame_width>>1;dst_height=frame_height>>1;
                src_slot=2'd0;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd60;parameter_block=5'd0;
            end
            5'd1:begin // encoder2.conv3x3_s2
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd5;cin=6'd12;cout=6'd24;
                src_width=frame_width>>1;src_height=frame_height>>1;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd0;dst_slot=2'd1;skip_slot=2'd0;parameter_beats=16'd360;parameter_block=5'd1;
            end
            5'd2:begin // res0.expand1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd24;cout=6'd48;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd1;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd240;parameter_block=5'd2;
            end
            5'd3:begin // res0.depthwise3x3
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd2;cin=6'd48;cout=6'd48;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd0;dst_slot=2'd2;skip_slot=2'd0;parameter_beats=16'd144;parameter_block=5'd3;
            end
            5'd4:begin // res0.project1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd48;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd2;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd168;parameter_block=5'd4;
            end
            5'd5:begin // res0.add_relu
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd3;cin=6'd24;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd0;dst_slot=2'd2;skip_slot=2'd1;parameter_beats=16'd0;parameter_block=5'd5;
            end
            5'd6:begin // res1.expand1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd24;cout=6'd48;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd2;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd240;parameter_block=5'd6;
            end
            5'd7:begin // res1.depthwise3x3
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd2;cin=6'd48;cout=6'd48;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd0;dst_slot=2'd1;skip_slot=2'd0;parameter_beats=16'd144;parameter_block=5'd7;
            end
            5'd8:begin // res1.project1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd48;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd1;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd168;parameter_block=5'd8;
            end
            5'd9:begin // res1.add_relu
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd3;cin=6'd24;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd0;dst_slot=2'd1;skip_slot=2'd2;parameter_beats=16'd0;parameter_block=5'd9;
            end
            5'd10:begin // res2.expand1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd24;cout=6'd48;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd1;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd240;parameter_block=5'd10;
            end
            5'd11:begin // res2.depthwise3x3
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd2;cin=6'd48;cout=6'd48;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd0;dst_slot=2'd2;skip_slot=2'd0;parameter_beats=16'd144;parameter_block=5'd11;
            end
            5'd12:begin // res2.project1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd48;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd2;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd168;parameter_block=5'd12;
            end
            5'd13:begin // res2.add_relu
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd3;cin=6'd24;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>2;dst_height=frame_height>>2;
                src_slot=2'd0;dst_slot=2'd2;skip_slot=2'd1;parameter_beats=16'd0;parameter_block=5'd13;
            end
            5'd14:begin // decoder1.upsample2
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=1;
                mode=3'd0;cin=6'd24;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>1;dst_height=frame_height>>1;
                src_slot=2'd2;dst_slot=2'd2;skip_slot=2'd0;parameter_beats=16'd0;parameter_block=5'd14;
            end
            5'd15:begin // decoder1.depthwise3x3
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=1;view=0;
                mode=3'd2;cin=6'd24;cout=6'd24;
                src_width=frame_width>>2;src_height=frame_height>>2;dst_width=frame_width>>1;dst_height=frame_height>>1;
                src_slot=2'd2;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd72;parameter_block=5'd15;
            end
            5'd16:begin // decoder1.pointwise1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd24;cout=6'd16;
                src_width=frame_width>>1;src_height=frame_height>>1;dst_width=frame_width>>1;dst_height=frame_height>>1;
                src_slot=2'd0;dst_slot=2'd1;skip_slot=2'd0;parameter_beats=16'd80;parameter_block=5'd16;
            end
            5'd17:begin // decoder2.upsample2
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=1;
                mode=3'd0;cin=6'd16;cout=6'd16;
                src_width=frame_width>>1;src_height=frame_height>>1;dst_width=frame_width>>0;dst_height=frame_height>>0;
                src_slot=2'd1;dst_slot=2'd1;skip_slot=2'd0;parameter_beats=16'd0;parameter_block=5'd17;
            end
            5'd18:begin // decoder2.depthwise3x3
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=1;view=0;
                mode=3'd2;cin=6'd16;cout=6'd16;
                src_width=frame_width>>1;src_height=frame_height>>1;dst_width=frame_width>>0;dst_height=frame_height>>0;
                src_slot=2'd1;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd48;parameter_block=5'd18;
            end
            5'd19:begin // decoder2.pointwise1x1
                valid=1;last=0;input_rgb=0;output_rgb=0;virtual_up2=0;view=0;
                mode=3'd0;cin=6'd16;cout=6'd8;
                src_width=frame_width>>0;src_height=frame_height>>0;dst_width=frame_width>>0;dst_height=frame_height>>0;
                src_slot=2'd0;dst_slot=2'd1;skip_slot=2'd0;parameter_beats=16'd24;parameter_block=5'd19;
            end
            5'd20:begin // output.conv3x3
                valid=1;last=0;input_rgb=0;output_rgb=1;virtual_up2=0;view=0;
                mode=3'd1;cin=6'd8;cout=6'd3;
                src_width=frame_width>>0;src_height=frame_height>>0;dst_width=frame_width>>0;dst_height=frame_height>>0;
                src_slot=2'd1;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd33;parameter_block=5'd20;
            end
            5'd21:begin // output.s8_to_rgb
                valid=1;last=1;input_rgb=0;output_rgb=0;virtual_up2=0;view=1;
                mode=3'd0;cin=6'd3;cout=6'd3;
                src_width=frame_width>>0;src_height=frame_height>>0;dst_width=frame_width>>0;dst_height=frame_height>>0;
                src_slot=2'd0;dst_slot=2'd0;skip_slot=2'd0;parameter_beats=16'd0;parameter_block=5'd21;
            end
            default:begin end
        endcase
    end
endmodule
