// C29 capacity candidate; retained C28 baseline unchanged.
// C26 actual camera/ROI/CDC host branch; retained C24 untouched.
// C24 independent Resize/Capture integration; retained C22 sources unchanged.
// C22 independent feature-overlay branch; retained C21 sources unchanged.
// C21 independent six-lane weight branch; retained C18 sources unchanged.
// C18 independent generated-plan integration. Retained C12/C14/C15 RTL is unchanged.
`timescale 1ns/1ps
// C18 generated-plan video core + retained C13 CPU adapter and APB3/IRQ.
// Normal noncoherent DDR subset only; no actual CPU IP or PHY. Camera CDC is included.
// The 16-bit APB address is a LOCAL window offset; board/BSP decoding must
// be verified. CACHE/PROT/QOS semantics and exclusive/atomic accesses are
// not provided by the normalized fabric. See the C13 adapter contract.
module c1_r2_camera_capacity_host_system #(
    parameter integer CPU_ID_WIDTH=8,WIDTH=640,HEIGHT=480,CAPTURE_FIFO=256,DISPLAY_FIFO=512,FIFO_DEPTH=8,
    parameter integer SOURCE_WIDTH=1920,SOURCE_HEIGHT=1080,ROI_X=240,ROI_Y=0,ROI_WIDTH=1440,ROI_HEIGHT=1080,
    parameter integer CAMERA_FIFO=512,FRAME_TIMEOUT=5000000,
    parameter logic [31:0] ARENA_BASE=32'h08000000
) (
    input wire clk,rst,platform_ready,psel,penable,pwrite,
    input wire [15:0] paddr,
    input wire [31:0] pwdata,
    output wire [31:0] prdata,
    output wire pready,pslverr,irq,
    input wire cam_clk,cam_rst,cam_valid,cam_sof,cam_eol,cam_eof,cam_error,
    input wire [23:0] cam_rgb,
    input wire camera_cancel,
    output wire camera_busy,camera_config_error,camera_snapshot_valid,
    output wire [31:0] camera_seen,camera_skipped,
    output wire [15:0] camera_fifo_peak,
    output wire camera_result_valid,camera_result_failed,camera_result_admitted,
    output wire [3:0] camera_result_code,
    output wire [31:0] camera_result_tag,
    input wire display_request,
    output wire display_request_ready,
    input wire p_req,p_sof,p_eol,p_eof,
    output wire m_valid,m_sof,m_eol,m_eof,
    output wire [23:0] m_rgb,
    output wire front_valid,display_frame_armed,
    output wire [31:0] display_pair_tag,
    output wire nn_complete,nn_failed,
    output wire [31:0] nn_result_tag,nn_result_cycles,
    output wire fabric_error,
    output wire [7:0] physical_read_outstanding,physical_write_outstanding,
    input wire [31:0] cpu_araddr,
    input wire [7:0] cpu_arlen,
    input wire [2:0] cpu_arsize,
    input wire [1:0] cpu_arburst,
    input wire cpu_arvalid,
    output wire cpu_arready,
    output wire [127:0] cpu_rdata,
    output wire [1:0] cpu_rresp,
    output wire cpu_rlast,
    output wire cpu_rvalid,
    input wire cpu_rready,
    input wire [31:0] cpu_awaddr,
    input wire [7:0] cpu_awlen,
    input wire [2:0] cpu_awsize,
    input wire [1:0] cpu_awburst,
    input wire cpu_awvalid,
    output wire cpu_awready,
    input wire [127:0] cpu_wdata,
    input wire [15:0] cpu_wstrb,
    input wire cpu_wlast,
    input wire cpu_wvalid,
    output wire cpu_wready,
    output wire [1:0] cpu_bresp,
    output wire cpu_bvalid,
    input wire cpu_bready,
    output wire [3:0] m_axi_arid,
    output wire [31:0] m_axi_araddr,
    output wire [7:0] m_axi_arlen,
    output wire [2:0] m_axi_arsize,
    output wire [1:0] m_axi_arburst,
    output wire m_axi_arlock,
    output wire [3:0] m_axi_arcache,m_axi_arqos,
    output wire [2:0] m_axi_arprot,
    output wire m_axi_arvalid,
    input wire m_axi_arready,
    input wire [3:0] m_axi_rid,
    input wire [127:0] m_axi_rdata,
    input wire [1:0] m_axi_rresp,
    input wire m_axi_rlast,m_axi_rvalid,
    output wire m_axi_rready,
    output wire [3:0] m_axi_awid,
    output wire [31:0] m_axi_awaddr,
    output wire [7:0] m_axi_awlen,
    output wire [2:0] m_axi_awsize,
    output wire [1:0] m_axi_awburst,
    output wire m_axi_awlock,
    output wire [3:0] m_axi_awcache,m_axi_awqos,
    output wire [2:0] m_axi_awprot,
    output wire m_axi_awvalid,
    input wire m_axi_awready,
    output wire [127:0] m_axi_wdata,
    output wire [15:0] m_axi_wstrb,
    output wire m_axi_wlast,m_axi_wvalid,
    input wire m_axi_wready,
    input wire [3:0] m_axi_bid,
    input wire [1:0] m_axi_bresp,
    input wire m_axi_bvalid,
    output wire m_axi_bready,
    input wire [CPU_ID_WIDTH-1:0] cpu_arid,cpu_awid,
    input wire cpu_arlock,cpu_awlock,
    input wire [3:0] cpu_arregion,cpu_awregion,
    output wire [CPU_ID_WIDTH-1:0] cpu_rid,cpu_bid,
    output wire cpu_adapter_busy,cpu_adapter_fault
);
    wire  core_psel;
    wire  core_penable;
    wire  core_pwrite;
    wire [7:0] core_paddr;
    wire [31:0] core_pwdata;
    wire [3:0] core_pstrb;
    wire [31:0] core_prdata;
    wire  core_pready;
    wire  core_pslverr;
    wire  core_irq;
    wire [31:0] core_cpu_araddr;
    wire [7:0] core_cpu_arlen;
    wire [2:0] core_cpu_arsize;
    wire [1:0] core_cpu_arburst;
    wire  core_cpu_arvalid;
    wire  core_cpu_arready;
    wire [127:0] core_cpu_rdata;
    wire [1:0] core_cpu_rresp;
    wire  core_cpu_rlast;
    wire  core_cpu_rvalid;
    wire  core_cpu_rready;
    wire [31:0] core_cpu_awaddr;
    wire [7:0] core_cpu_awlen;
    wire [2:0] core_cpu_awsize;
    wire [1:0] core_cpu_awburst;
    wire  core_cpu_awvalid;
    wire  core_cpu_awready;
    wire [127:0] core_cpu_wdata;
    wire [15:0] core_cpu_wstrb;
    wire  core_cpu_wlast;
    wire  core_cpu_wvalid;
    wire  core_cpu_wready;
    wire [1:0] core_cpu_bresp;
    wire  core_cpu_bvalid;
    wire  core_cpu_bready;
    c1_r2_cpu_axi_adapter #(.ID_WIDTH(CPU_ID_WIDTH)) u_cpu_adapter (
        .clk(clk),.rst(rst),.busy(cpu_adapter_busy),.protocol_error(cpu_adapter_fault),
        .s_araddr(cpu_araddr),
        .m_araddr(core_cpu_araddr),
        .s_arlen(cpu_arlen),
        .m_arlen(core_cpu_arlen),
        .s_arsize(cpu_arsize),
        .m_arsize(core_cpu_arsize),
        .s_arburst(cpu_arburst),
        .m_arburst(core_cpu_arburst),
        .s_arvalid(cpu_arvalid),
        .m_arvalid(core_cpu_arvalid),
        .s_arready(cpu_arready),
        .m_arready(core_cpu_arready),
        .s_rdata(cpu_rdata),
        .m_rdata(core_cpu_rdata),
        .s_rresp(cpu_rresp),
        .m_rresp(core_cpu_rresp),
        .s_rlast(cpu_rlast),
        .m_rlast(core_cpu_rlast),
        .s_rvalid(cpu_rvalid),
        .m_rvalid(core_cpu_rvalid),
        .s_rready(cpu_rready),
        .m_rready(core_cpu_rready),
        .s_awaddr(cpu_awaddr),
        .m_awaddr(core_cpu_awaddr),
        .s_awlen(cpu_awlen),
        .m_awlen(core_cpu_awlen),
        .s_awsize(cpu_awsize),
        .m_awsize(core_cpu_awsize),
        .s_awburst(cpu_awburst),
        .m_awburst(core_cpu_awburst),
        .s_awvalid(cpu_awvalid),
        .m_awvalid(core_cpu_awvalid),
        .s_awready(cpu_awready),
        .m_awready(core_cpu_awready),
        .s_wdata(cpu_wdata),
        .m_wdata(core_cpu_wdata),
        .s_wstrb(cpu_wstrb),
        .m_wstrb(core_cpu_wstrb),
        .s_wlast(cpu_wlast),
        .m_wlast(core_cpu_wlast),
        .s_wvalid(cpu_wvalid),
        .m_wvalid(core_cpu_wvalid),
        .s_wready(cpu_wready),
        .m_wready(core_cpu_wready),
        .s_bresp(cpu_bresp),
        .m_bresp(core_cpu_bresp),
        .s_bvalid(cpu_bvalid),
        .m_bvalid(core_cpu_bvalid),
        .s_bready(cpu_bready),
        .m_bready(core_cpu_bready),
        .s_arid(cpu_arid),
        .s_awid(cpu_awid),
        .s_arlock(cpu_arlock),
        .s_awlock(cpu_awlock),
        .s_arregion(cpu_arregion),
        .s_awregion(cpu_awregion),
        .s_rid(cpu_rid),
        .s_bid(cpu_bid)
    );
    c1_r2_host_control_bridge u_control_bridge (
        .rst(rst),.cpu_adapter_busy(cpu_adapter_busy),.cpu_adapter_fault(cpu_adapter_fault),
        .psel(psel),
        .core_psel(core_psel),
        .penable(penable),
        .core_penable(core_penable),
        .pwrite(pwrite),
        .core_pwrite(core_pwrite),
        .paddr(paddr),
        .core_paddr(core_paddr),
        .pwdata(pwdata),
        .core_pwdata(core_pwdata),
        .core_pstrb(core_pstrb),
        .prdata(prdata),
        .core_prdata(core_prdata),
        .pready(pready),
        .core_pready(core_pready),
        .pslverr(pslverr),
        .core_pslverr(core_pslverr),
        .irq(irq),
        .core_irq(core_irq)
    );
    c1_r2_video_camera_capacity_system #(.WIDTH(WIDTH),.HEIGHT(HEIGHT),.CAPTURE_FIFO(CAPTURE_FIFO),
        .DISPLAY_FIFO(DISPLAY_FIFO),.FIFO_DEPTH(FIFO_DEPTH),.ARENA_BASE(ARENA_BASE),
        .SOURCE_WIDTH(SOURCE_WIDTH),.SOURCE_HEIGHT(SOURCE_HEIGHT),.ROI_X(ROI_X),.ROI_Y(ROI_Y),
        .ROI_WIDTH(ROI_WIDTH),.ROI_HEIGHT(ROI_HEIGHT),.CAMERA_FIFO(CAMERA_FIFO),.FRAME_TIMEOUT(FRAME_TIMEOUT)) u_system (
        .clk(clk),
        .rst(rst),
        .platform_ready(platform_ready),
        .psel(core_psel),
        .penable(core_penable),
        .pwrite(core_pwrite),
        .paddr(core_paddr),
        .pwdata(core_pwdata),
        .pstrb(core_pstrb),
        .prdata(core_prdata),
        .pready(core_pready),
        .pslverr(core_pslverr),
        .irq(core_irq),
        .cam_clk(cam_clk),.cam_rst(cam_rst),.cam_valid(cam_valid),.cam_sof(cam_sof),.cam_eol(cam_eol),.cam_eof(cam_eof),
        .cam_error(cam_error),.cam_rgb(cam_rgb),.camera_cancel(camera_cancel),
        .camera_busy(camera_busy),.camera_config_error(camera_config_error),.camera_snapshot_valid(camera_snapshot_valid),
        .camera_seen(camera_seen),.camera_skipped(camera_skipped),.camera_fifo_peak(camera_fifo_peak),
        .camera_result_valid(camera_result_valid),.camera_result_failed(camera_result_failed),
        .camera_result_admitted(camera_result_admitted),.camera_result_code(camera_result_code),.camera_result_tag(camera_result_tag),
        .display_request(display_request),
        .display_request_ready(display_request_ready),
        .p_req(p_req),
        .p_sof(p_sof),
        .p_eol(p_eol),
        .p_eof(p_eof),
        .m_valid(m_valid),
        .m_sof(m_sof),
        .m_eol(m_eol),
        .m_eof(m_eof),
        .m_rgb(m_rgb),
        .front_valid(front_valid),
        .display_frame_armed(display_frame_armed),
        .display_pair_tag(display_pair_tag),
        .nn_complete(nn_complete),
        .nn_failed(nn_failed),
        .nn_result_tag(nn_result_tag),
        .nn_result_cycles(nn_result_cycles),
        .fabric_error(fabric_error),
        .physical_read_outstanding(physical_read_outstanding),
        .physical_write_outstanding(physical_write_outstanding),
        .cpu_araddr(core_cpu_araddr),
        .cpu_arlen(core_cpu_arlen),
        .cpu_arsize(core_cpu_arsize),
        .cpu_arburst(core_cpu_arburst),
        .cpu_arvalid(core_cpu_arvalid),
        .cpu_arready(core_cpu_arready),
        .cpu_rdata(core_cpu_rdata),
        .cpu_rresp(core_cpu_rresp),
        .cpu_rlast(core_cpu_rlast),
        .cpu_rvalid(core_cpu_rvalid),
        .cpu_rready(core_cpu_rready),
        .cpu_awaddr(core_cpu_awaddr),
        .cpu_awlen(core_cpu_awlen),
        .cpu_awsize(core_cpu_awsize),
        .cpu_awburst(core_cpu_awburst),
        .cpu_awvalid(core_cpu_awvalid),
        .cpu_awready(core_cpu_awready),
        .cpu_wdata(core_cpu_wdata),
        .cpu_wstrb(core_cpu_wstrb),
        .cpu_wlast(core_cpu_wlast),
        .cpu_wvalid(core_cpu_wvalid),
        .cpu_wready(core_cpu_wready),
        .cpu_bresp(core_cpu_bresp),
        .cpu_bvalid(core_cpu_bvalid),
        .cpu_bready(core_cpu_bready),
        .m_axi_arid(m_axi_arid),
        .m_axi_araddr(m_axi_araddr),
        .m_axi_arlen(m_axi_arlen),
        .m_axi_arsize(m_axi_arsize),
        .m_axi_arburst(m_axi_arburst),
        .m_axi_arlock(m_axi_arlock),
        .m_axi_arcache(m_axi_arcache),
        .m_axi_arqos(m_axi_arqos),
        .m_axi_arprot(m_axi_arprot),
        .m_axi_arvalid(m_axi_arvalid),
        .m_axi_arready(m_axi_arready),
        .m_axi_rid(m_axi_rid),
        .m_axi_rdata(m_axi_rdata),
        .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast),
        .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready),
        .m_axi_awid(m_axi_awid),
        .m_axi_awaddr(m_axi_awaddr),
        .m_axi_awlen(m_axi_awlen),
        .m_axi_awsize(m_axi_awsize),
        .m_axi_awburst(m_axi_awburst),
        .m_axi_awlock(m_axi_awlock),
        .m_axi_awcache(m_axi_awcache),
        .m_axi_awqos(m_axi_awqos),
        .m_axi_awprot(m_axi_awprot),
        .m_axi_awvalid(m_axi_awvalid),
        .m_axi_awready(m_axi_awready),
        .m_axi_wdata(m_axi_wdata),
        .m_axi_wstrb(m_axi_wstrb),
        .m_axi_wlast(m_axi_wlast),
        .m_axi_wvalid(m_axi_wvalid),
        .m_axi_wready(m_axi_wready),
        .m_axi_bid(m_axi_bid),
        .m_axi_bresp(m_axi_bresp),
        .m_axi_bvalid(m_axi_bvalid),
        .m_axi_bready(m_axi_bready)
    );
endmodule
