// Small-IO wrapper around the real C8 depthwise core.  It is used only for
// boardless Efinity PNR/timing: the wide tensor/weight buses are generated by
// registers inside the wrapper, so auto pin assignment is not the limiting
// factor.  The core itself is unchanged and remains the measured object.
module c1_ti60_dw_leaf_wrapper (
    input  logic        clk,
    input  logic        rst,
    output logic [31:0] checksum,
    output logic        done_seen
);
    logic start_valid;
    logic start_ready;
    logic [575:0] start_weights;
    logic [255:0] start_bias;
    logic [143:0] start_mult;
    logic [47:0] start_shift;
    logic [15:0] start_activation;
    logic in_valid, in_ready;
    logic [575:0] in_window;
    logic in_sof, in_eol, in_eof;
    logic [15:0] in_x, in_y;
    logic out_valid, out_ready;
    logic [63:0] out_data;
    logic out_sof, out_eol, out_eof;
    logic [15:0] out_x, out_y;
    logic core_busy, core_done, core_overflow;
    logic [31:0] cycle_q;
    logic [7:0] beat_q;

    assign out_ready = 1'b1;

    always @(posedge clk) begin
        if (rst) begin
            start_valid <= 1'b0;
            start_weights <= '0;
            start_bias <= '0;
            start_mult <= '0;
            start_shift <= '0;
            start_activation <= 16'h5555;
            in_valid <= 1'b0;
            in_window <= '0;
            in_sof <= 1'b0;
            in_eol <= 1'b0;
            in_eof <= 1'b0;
            in_x <= '0;
            in_y <= '0;
            cycle_q <= 32'd1;
            beat_q <= 8'd0;
            checksum <= 32'd0;
            done_seen <= 1'b0;
        end else begin
            cycle_q <= cycle_q + 32'd1;
            start_valid <= (!core_busy && !start_valid);
            if (start_valid && start_ready) begin
                start_weights <= {72{cycle_q[7:0]}};
                start_bias <= {8{cycle_q}};
                start_mult <= {8{18'h10001}};
                start_shift <= {8{6'd8}};
                start_activation <= 16'h5555;
                beat_q <= 8'd0;
            end
            in_valid <= core_busy;
            in_sof <= core_busy && (beat_q == 8'd0);
            in_eol <= core_busy;
            in_eof <= core_busy && (beat_q == 8'd15);
            in_x <= {8'd0, beat_q};
            in_y <= 16'd0;
            in_window <= {72{cycle_q[7:0]}};
            if (core_busy && in_ready)
                beat_q <= beat_q + 8'd1;
            if (out_valid) begin
                checksum <= checksum ^ out_data ^ {31'd0, out_eof} ^
                            {16'd0, out_y} ^ {16'd0, out_x};
                if (out_eof)
                    done_seen <= 1'b1;
            end
        end
    end

    c1_dwconv3x3_c8_requant_core #(.X_BITS(16), .Y_BITS(16)) u_core (
        .clk(clk), .rst(rst),
        .start_valid(start_valid), .start_ready(start_ready),
        .start_weights_s8(start_weights), .start_bias_s32(start_bias),
        .start_mult_s18(start_mult), .start_shift_u6(start_shift),
        .start_activation(start_activation),
        .in_valid(in_valid), .in_ready(in_ready), .in_window_s8(in_window),
        .in_sof(in_sof), .in_eol(in_eol), .in_eof(in_eof),
        .in_x(in_x), .in_y(in_y),
        .out_valid(out_valid), .out_ready(out_ready),
        .out_data_s8(out_data), .out_sof(out_sof), .out_eol(out_eol),
        .out_eof(out_eof), .out_x(out_x), .out_y(out_y),
        .busy(core_busy), .done(core_done), .overflow_seen(core_overflow)
    );
endmodule
