`timescale 1ns/1ps

// Board-independent nearest-neighbour x2 upsample engine for one C8 INT8
// pixel per input beat.  Channel 0 occupies bits [7:0].
//
// A start_valid/start_ready handshake snapshots the non-zero input width and
// height.  Width must not exceed MAX_WIDTH.  The input stream then supplies
// exactly width*height raster-order 64-bit pixels; coordinates and frame
// markers are generated by this engine.
//
// One complete source line is captured into a portable synchronous RAM before
// replay.  Each source pixel is emitted twice horizontally, and the complete
// buffered line is replayed twice vertically.  Capture and replay are
// intentionally time-multiplexed in this baseline, so the next input line is
// back-pressured until both output rows have been consumed.  A prefetch issued
// when horizontal copy 0 is consumed permits one output beat per cycle after
// the initial synchronous-RAM load.
//
// abort synchronously discards the active frame and any held output.  RAM is
// never reset; every replayed location has first been overwritten by capture.
// done pulses only on consumption of the final output beat.
module c1_s8_upsample2_c8 #(
    parameter integer MAX_WIDTH = 640
) (
    input  logic          clk,
    input  logic          rst,
    input  logic          abort,

    input  logic          start_valid,
    output logic          start_ready,
    input  logic [15:0]   cfg_input_width,
    input  logic [15:0]   cfg_input_height,
    output logic          start_error,
    output logic [1:0]    start_error_code,
    output logic          busy,
    output logic          done,

    input  logic          in_valid,
    output logic          in_ready,
    input  logic [63:0]   in_data_s8,

    output logic          out_valid,
    input  logic          out_ready,
    output logic [63:0]   out_data_s8,
    output logic          out_sof,
    output logic          out_eol,
    output logic          out_eof,
    output logic [16:0]   out_x,
    output logic [16:0]   out_y
);

    localparam logic [1:0] START_ERR_NONE = 2'd0;
    localparam logic [1:0] START_ERR_ZERO_DIMENSION = 2'd1;
    localparam logic [1:0] START_ERR_WIDTH_EXCEEDS_MAX = 2'd2;
    localparam integer RAM_ADDR_WIDTH =
        (MAX_WIDTH <= 1) ? 1 : $clog2(MAX_WIDTH);

    typedef enum logic [2:0] {
        STATE_IDLE,
        STATE_CAPTURE,
        STATE_PRIME_READ,
        STATE_LOAD_PIXEL,
        STATE_PLAY
    } state_t;

    state_t state;
    logic [15:0] width_q;
    logic [15:0] height_q;
    logic [15:0] capture_x;
    logic [15:0] line_y;
    logic [15:0] play_x;
    logic horizontal_copy;
    logic vertical_copy;
    logic [63:0] play_data_q;

    logic ram_rd_en;
    logic [RAM_ADDR_WIDTH-1:0] ram_rd_addr;
    logic [63:0] ram_rd_data;
    logic ram_wr_en;
    logic [RAM_ADDR_WIDTH-1:0] ram_wr_addr;
    logic [63:0] ram_wr_data;
    logic play_has_next;
    logic [15:0] play_next_x;
    logic output_fire;
    logic input_fire;

    always_comb begin
        start_ready = !rst && !abort && (state == STATE_IDLE);
        busy = (state != STATE_IDLE);
        in_ready = !abort && (state == STATE_CAPTURE);
        input_fire = in_valid && in_ready;

        out_valid = !abort && (state == STATE_PLAY);
        output_fire = out_valid && out_ready;
        out_data_s8 = play_data_q;
        out_x = ({1'b0, play_x} << 1) + horizontal_copy;
        out_y = ({1'b0, line_y} << 1) + vertical_copy;
        out_sof = out_valid && (line_y == 0) && !vertical_copy &&
                  (play_x == 0) && !horizontal_copy;
        out_eol = out_valid && (play_x == width_q - 16'd1) &&
                  horizontal_copy;
        out_eof = out_valid && (line_y == height_q - 16'd1) &&
                  vertical_copy && (play_x == width_q - 16'd1) &&
                  horizontal_copy;

        ram_wr_en = input_fire;
        ram_wr_addr = capture_x[RAM_ADDR_WIDTH-1:0];
        ram_wr_data = in_data_s8;

        play_has_next = (play_x != width_q - 16'd1) || !vertical_copy;
        if (play_x == width_q - 16'd1)
            play_next_x = 16'd0;
        else
            play_next_x = play_x + 16'd1;

        ram_rd_en = 1'b0;
        ram_rd_addr = '0;
        if (state == STATE_PRIME_READ) begin
            ram_rd_en = 1'b1;
            ram_rd_addr = '0;
        end else if ((state == STATE_PLAY) && output_fire &&
                     !horizontal_copy && play_has_next) begin
            ram_rd_en = 1'b1;
            ram_rd_addr = play_next_x[RAM_ADDR_WIDTH-1:0];
        end
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            state <= STATE_IDLE;
            width_q <= 16'd0;
            height_q <= 16'd0;
            capture_x <= 16'd0;
            line_y <= 16'd0;
            play_x <= 16'd0;
            horizontal_copy <= 1'b0;
            vertical_copy <= 1'b0;
            play_data_q <= 64'd0;
            start_error <= 1'b0;
            start_error_code <= START_ERR_NONE;
            done <= 1'b0;
        end else if (abort) begin
            state <= STATE_IDLE;
            width_q <= 16'd0;
            height_q <= 16'd0;
            capture_x <= 16'd0;
            line_y <= 16'd0;
            play_x <= 16'd0;
            horizontal_copy <= 1'b0;
            vertical_copy <= 1'b0;
            play_data_q <= 64'd0;
            start_error <= 1'b0;
            start_error_code <= START_ERR_NONE;
            done <= 1'b0;
        end else begin
            start_error <= 1'b0;
            start_error_code <= START_ERR_NONE;
            done <= 1'b0;

            case (state)
                STATE_IDLE: begin
                    if (start_valid && start_ready) begin
                        if ((cfg_input_width == 0) ||
                            (cfg_input_height == 0)) begin
                            start_error <= 1'b1;
                            start_error_code <= START_ERR_ZERO_DIMENSION;
                        end else if (cfg_input_width > MAX_WIDTH) begin
                            start_error <= 1'b1;
                            start_error_code <= START_ERR_WIDTH_EXCEEDS_MAX;
                        end else begin
                            width_q <= cfg_input_width;
                            height_q <= cfg_input_height;
                            capture_x <= 16'd0;
                            line_y <= 16'd0;
                            play_x <= 16'd0;
                            horizontal_copy <= 1'b0;
                            vertical_copy <= 1'b0;
                            state <= STATE_CAPTURE;
                        end
                    end
                end

                STATE_CAPTURE: begin
                    if (input_fire) begin
                        if (capture_x == width_q - 16'd1) begin
                            capture_x <= 16'd0;
                            state <= STATE_PRIME_READ;
                        end else begin
                            capture_x <= capture_x + 16'd1;
                        end
                    end
                end

                STATE_PRIME_READ: begin
                    // rd_data updates on this edge in the synchronous RAM.
                    state <= STATE_LOAD_PIXEL;
                end

                STATE_LOAD_PIXEL: begin
                    play_data_q <= ram_rd_data;
                    play_x <= 16'd0;
                    horizontal_copy <= 1'b0;
                    vertical_copy <= 1'b0;
                    state <= STATE_PLAY;
                end

                STATE_PLAY: begin
                    if (output_fire) begin
                        if (!horizontal_copy) begin
                            // The next source pixel (or x=0 for the second
                            // output row) is prefetched by combinational RAM
                            // control on this same handshake.
                            horizontal_copy <= 1'b1;
                        end else begin
                            horizontal_copy <= 1'b0;
                            if (play_x != width_q - 16'd1) begin
                                play_x <= play_x + 16'd1;
                                play_data_q <= ram_rd_data;
                            end else if (!vertical_copy) begin
                                play_x <= 16'd0;
                                vertical_copy <= 1'b1;
                                play_data_q <= ram_rd_data;
                            end else if (line_y != height_q - 16'd1) begin
                                line_y <= line_y + 16'd1;
                                capture_x <= 16'd0;
                                vertical_copy <= 1'b0;
                                play_x <= 16'd0;
                                state <= STATE_CAPTURE;
                            end else begin
                                // This branch is reached only on the final
                                // out_eof handshake.
                                state <= STATE_IDLE;
                                done <= 1'b1;
                            end
                        end
                    end
                end

                default: begin
                    state <= STATE_IDLE;
                    start_error <= 1'b1;
                    start_error_code <= START_ERR_ZERO_DIMENSION;
                end
            endcase
        end
    end

    c1_ram_sdp_read_first #(
        .DATA_WIDTH(64),
        .DEPTH(MAX_WIDTH),
        .ADDR_WIDTH(RAM_ADDR_WIDTH)
    ) u_line_ram (
        .clk,
        .rd_en(ram_rd_en),
        .rd_addr(ram_rd_addr),
        .rd_data(ram_rd_data),
        .wr_en(ram_wr_en),
        .wr_addr(ram_wr_addr),
        .wr_data(ram_wr_data)
    );

`ifndef SYNTHESIS
    initial begin
        if ((MAX_WIDTH < 1) || (MAX_WIDTH > 65535))
            $fatal(1, "c1_s8_upsample2_c8 MAX_WIDTH must be 1..65535");
        if ((1 << RAM_ADDR_WIDTH) < MAX_WIDTH)
            $fatal(1, "c1_s8_upsample2_c8 RAM_ADDR_WIDTH is too small");
    end

    always_ff @(posedge clk) begin
        if (!rst && !abort) begin
            if (done && busy)
                $fatal(1, "c1_s8_upsample2_c8 done asserted while busy");
            if (out_eof && !(out_valid &&
                (out_x == ({1'b0, width_q} << 1) - 17'd1) &&
                (out_y == ({1'b0, height_q} << 1) - 17'd1)))
                $fatal(1, "c1_s8_upsample2_c8 EOF coordinate mismatch");
        end
    end
`endif

endmodule
